services:
  api:
    labels:
      - traefik.docker.network=coolify
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - API_TOKEN=${API_TOKEN}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-1}
      - DATABASE_URL=mysql+aiomysql://${MARIADB_USER}:${MARIADB_PASSWORD}@rc-db:3306/${MARIADB_DATABASE}
      - CLANIMG_API_URL=${CLANIMG_API_URL:-}
      - CLANIMG_API_TOKEN=${CLANIMG_API_TOKEN:-}
    depends_on:
      - mariadb
    networks:
      - network
      - coolify
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      network:
        aliases:
          - rc-db
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST:-rc-db}
      - PMA_PORT=${PMA_PORT:-3306}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge
  coolify:
    external: true

volumes:
  mysql_data: