services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-template
    expose:
      - "8000"
    environment:
      - API_TOKEN=${API_TOKEN}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-2}
    networks:
      - network
    restart: unless-stopped

#  mariadb:
#    image: mysql:8.0
#    container_name: mariadb
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - network
#    restart: unless-stopped

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    environment:
#      - PMA_USER=${PMA_USER}
#      - PMA_PASSWORD=${PMA_PASSWORD}
#    depends_on:
#      - mariadb
#    networks:
#      - network
#    restart: unless-stopped

networks:
  network:
    driver: bridge

# volumes:
#  mysql_data: