#!/usr/bin/env python3
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TARGET_FOLDERS = [PROJECT_ROOT / "app"]

def ensure_init_files(base_dir: Path):
    created = 0
    for root, dirs, files in os.walk(base_dir):
        dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']
        if "__init__.py" not in files:
            init_path = Path(root) / "__init__.py"
            with open(init_path, "w", encoding="utf-8") as f:
                f.write("# Auto-generated by .api/build.py\n")
            print(f"Hinzugefügt: {init_path.relative_to(PROJECT_ROOT)}")
            created += 1
    return created

if __name__ == "__main__":
    print("Starte Build-Vorgang...")
    total = 0
    for folder in TARGET_FOLDERS:
        if folder.exists():
            total += ensure_init_files(folder)
        else:
            print(f"Überspringe {folder} – Ordner nicht gefunden.")
    print(f"Build abgeschlossen. ({total} __init__.py-Dateien erstellt oder bestätigt)")
